# Generated by Django 5.2.5 on 2025-08-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Admin'), ('editor', 'Editor'), ('volunteer', 'Volunteer')], default='volunteer', help_text="Designates the user's role within the application.", max_length=32),
        ),
    ]
