# Generated by Django 5.2.5 on 2025-08-15 22:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hsds_ext", "0001_enable_pg_trgm"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveOverlay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("location", "Location"),
                            ("service", "Service"),
                            ("service_at_location", "Service at Location"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("sensitive", models.BooleanField(default=False)),
                ("visibility_rules", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "hsds_ext_sensitive_overlays",
                "unique_together": {("entity_type", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="FieldVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("location", "Location"),
                            ("service", "Service"),
                            ("service_at_location", "Service at Location"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("field_path", models.TextField()),
                ("version", models.BigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hsds_ext_field_versions",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="hsds_ext_fi_entity__c7c01c_idx",
                    )
                ],
                "unique_together": {("entity_type", "entity_id", "field_path")},
            },
        ),
        migrations.CreateModel(
            name="VerificationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("location", "Location"),
                            ("service", "Service"),
                            ("service_at_location", "Service at Location"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                (
                    "field_path",
                    models.TextField(
                        help_text="Dot-path of the verified field within HSDS JSON."
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("called", "Called"),
                            ("website", "Website"),
                            ("onsite", "On-site"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hsds_ext_verification_events",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="hsds_ext_ve_entity__be2156_idx",
                    ),
                    models.Index(
                        fields=["-verified_at"], name="hsds_ext_ve_verifie_c94e0a_idx"
                    ),
                    models.Index(
                        fields=["field_path"], name="hsds_ext_ve_field_p_42136d_idx"
                    ),
                ],
            },
        ),
    ]
