# Generated by Django 5.2.5 on 2025-08-15 23:03

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hsds_ext", "0002_core_ext_tables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[("shelf", "Shelf"), ("siblings", "Siblings")],
                        max_length=16,
                    ),
                ),
                (
                    "targets",
                    models.JSONField(help_text="Target entities for the operation."),
                ),
                (
                    "patch",
                    models.JSONField(help_text="RFC6902 patch to apply to targets."),
                ),
                (
                    "preview",
                    models.JSONField(
                        blank=True, help_text="Precomputed preview data.", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("committed", "Committed"),
                            ("undone", "Undone"),
                        ],
                        default="staged",
                        max_length=16,
                    ),
                ),
                ("undo_token", models.TextField(blank=True, null=True)),
                ("committed_at", models.DateTimeField(blank=True, null=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hsds_ext_bulk_operations",
            },
        ),
        migrations.CreateModel(
            name="DraftResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(help_text="Composite HSDS payload for review."),
                ),
                ("review_note", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_resources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hsds_ext_draft_resources",
            },
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_shared", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hsds_ext_shelves",
            },
        ),
        migrations.CreateModel(
            name="TaxonomyExtension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("location", "Location"),
                            ("service", "Service"),
                            ("service_at_location", "Service at Location"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("namespace", models.TextField()),
                ("key", models.TextField()),
                ("value", models.JSONField()),
            ],
            options={
                "db_table": "hsds_ext_taxonomy_extensions",
                "unique_together": {("entity_type", "entity_id", "namespace", "key")},
            },
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_entity_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("location", "Location"),
                            ("service", "Service"),
                            ("service_at_location", "Service at Location"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_entity_id", models.UUIDField()),
                (
                    "patch",
                    models.JSONField(
                        help_text="RFC6902 patch against canonical HSDS JSON."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hsds_ext_change_requests",
                "indexes": [
                    models.Index(
                        fields=["status"], name="hsds_ext_ch_status_7b3006_idx"
                    ),
                    models.Index(
                        fields=["target_entity_type", "target_entity_id"],
                        name="hsds_ext_ch_target__a89748_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShelfMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("organization", "Organization"),
                            ("location", "Location"),
                            ("service", "Service"),
                            ("service_at_location", "Service at Location"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_members_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shelf",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="hsds_ext.shelf",
                    ),
                ),
            ],
            options={
                "db_table": "hsds_ext_shelf_members",
                "unique_together": {("shelf", "entity_type", "entity_id")},
            },
        ),
    ]
