# Generated by Django 5.2.5 on 2025-08-17 00:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hsds_ext", "0004_worklists"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="worklist",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
