# Generated by Django 5.2.5 on 2025-08-14 04:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("alternate_name", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("tax_status", models.TextField(blank=True, null=True)),
                ("tax_id", models.TextField(blank=True, null=True)),
                (
                    "year_incorporated",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("legal_status", models.TextField(blank=True, null=True)),
                ("logo", models.URLField(blank=True, null=True)),
                ("uri", models.URLField(blank=True, null=True)),
                (
                    "parent_organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_organizations",
                        to="hsds.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("postal", "Postal"),
                            ("virtual", "Virtual"),
                        ],
                        max_length=8,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("alternate_name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("transportation", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("external_identifier", models.TextField(blank=True, null=True)),
                ("external_identifier_type", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locations",
                        to="hsds.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("alternate_name", models.TextField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="hsds.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("alternate_name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("defunct", "Defunct"),
                            ("temporarily closed", "Temporarily Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("interpretation_services", models.TextField(blank=True, null=True)),
                ("application_process", models.TextField(blank=True, null=True)),
                ("fees_description", models.TextField(blank=True, null=True)),
                ("wait_time", models.TextField(blank=True, null=True)),
                ("fees", models.TextField(blank=True, null=True)),
                ("accreditations", models.TextField(blank=True, null=True)),
                ("eligibility_description", models.TextField(blank=True, null=True)),
                ("minimum_age", models.PositiveIntegerField(blank=True, null=True)),
                ("maximum_age", models.PositiveIntegerField(blank=True, null=True)),
                ("assured_date", models.DateField(blank=True, null=True)),
                (
                    "assurer_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("licenses", models.TextField(blank=True, null=True)),
                ("alert", models.TextField(blank=True, null=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="hsds.organization",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="hsds.program",
                    ),
                ),
            ],
        ),
    ]
