# Generated by Django 5.2.5 on 2025-08-14 06:34

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hsds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Taxonomy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("uri", models.URLField(blank=True, null=True)),
                ("version", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("scheme", models.TextField(blank=True, null=True)),
                ("identifier", models.TextField(blank=True, null=True)),
                ("uri", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Accessibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accessibilities",
                        to="hsds.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attention", models.TextField(blank=True, null=True)),
                ("address_1", models.TextField()),
                ("address_2", models.TextField(blank=True, null=True)),
                ("city", models.TextField()),
                ("region", models.TextField(blank=True, null=True)),
                ("state_province", models.TextField()),
                ("postal_code", models.TextField()),
                ("country", models.TextField()),
                (
                    "address_type",
                    models.CharField(
                        choices=[
                            ("physical", "Physical"),
                            ("postal", "Postal"),
                            ("virtual", "Virtual"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="hsds.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("department", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="hsds.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="hsds.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="hsds.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CostOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("option", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("amount_description", models.TextField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_options",
                        to="hsds.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Funding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.TextField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding",
                        to="hsds.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding",
                        to="hsds.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier_scheme", models.TextField(blank=True, null=True)),
                ("identifier_type", models.TextField()),
                ("identifier", models.TextField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="hsds.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.TextField()),
                ("extension", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("text", "Text"),
                            ("voice", "Voice"),
                            ("fax", "Fax"),
                            ("cell", "Cell"),
                            ("video", "Video"),
                            ("pager", "Pager"),
                            ("textphone", "Textphone"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="hsds.contact",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="hsds.location",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="hsds.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="hsds.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("code", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="hsds.location",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="hsds.service",
                    ),
                ),
                (
                    "phone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="hsds.phone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document", models.TextField()),
                ("uri", models.URLField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="hsds.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceAtLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_at_locations",
                        to="hsds.location",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_at_locations",
                        to="hsds.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("extent", models.TextField(blank=True, null=True)),
                ("extent_type", models.TextField(blank=True, null=True)),
                ("uri", models.URLField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="hsds.service",
                    ),
                ),
                (
                    "service_at_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_areas",
                        to="hsds.serviceatlocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("dtstart", models.DateField(blank=True, null=True)),
                ("timezone", models.CharField(blank=True, max_length=50, null=True)),
                ("until", models.DateField(blank=True, null=True)),
                ("count", models.IntegerField(blank=True, null=True)),
                (
                    "wkst",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MO", "Monday"),
                            ("TU", "Tuesday"),
                            ("WE", "Wednesday"),
                            ("TH", "Thursday"),
                            ("FR", "Friday"),
                            ("SA", "Saturday"),
                            ("SU", "Sunday"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "freq",
                    models.CharField(
                        blank=True,
                        choices=[("WEEKLY", "Weekly"), ("MONTHLY", "Monthly")],
                        max_length=7,
                        null=True,
                    ),
                ),
                ("interval", models.IntegerField(blank=True, null=True)),
                ("byday", models.TextField(blank=True, null=True)),
                ("byweekno", models.TextField(blank=True, null=True)),
                ("bymonthday", models.TextField(blank=True, null=True)),
                ("byyearday", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("opens_at", models.TimeField(blank=True, null=True)),
                ("closes_at", models.TimeField(blank=True, null=True)),
                ("schedule_link", models.URLField(blank=True, null=True)),
                ("attending_type", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="hsds.location",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="hsds.service",
                    ),
                ),
                (
                    "service_at_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="hsds.serviceatlocation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="phone",
            name="service_at_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phones",
                to="hsds.serviceatlocation",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="service_at_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="hsds.serviceatlocation",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="locations",
            field=models.ManyToManyField(
                blank=True,
                related_name="services",
                through="hsds.ServiceAtLocation",
                to="hsds.location",
            ),
        ),
        migrations.CreateModel(
            name="TaxonomyTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.TextField(blank=True, null=True)),
                ("name", models.TextField()),
                ("description", models.TextField()),
                ("taxonomy", models.TextField(blank=True, null=True)),
                ("language", models.TextField(blank=True, null=True)),
                ("term_uri", models.URLField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="hsds.taxonomyterm",
                    ),
                ),
                (
                    "taxonomy_object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms",
                        to="hsds.taxonomy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceCapacity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("available", models.PositiveIntegerField()),
                ("maximum", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacities",
                        to="hsds.service",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capacities",
                        to="hsds.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="URL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.TextField(blank=True, null=True)),
                ("url", models.URLField()),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_urls",
                        to="hsds.organization",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_urls",
                        to="hsds.service",
                    ),
                ),
            ],
        ),
    ]
