# Generated by Django 5.2.5 on 2025-08-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hsds", "0002_taxonomy_unit_accessibility_address_contact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessibility",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessibility",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessibility",
            name="details_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessibility",
            name="details_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="department_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="department_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="title_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costoption",
            name="amount_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costoption",
            name="amount_description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costoption",
            name="option_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="costoption",
            name="option_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="alternate_name_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="alternate_name_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="name_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="name_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="transportation_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="transportation_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="alternate_name_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="alternate_name_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="alternate_name_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="alternate_name_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="name_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="program",
            name="name_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="accreditations_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="accreditations_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="alert_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="alert_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="alternate_name_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="alternate_name_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="application_process_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="application_process_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="eligibility_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="eligibility_description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="fees_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="fees_description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="fees_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="fees_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="interpretation_services_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="interpretation_services_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="name_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="wait_time_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="wait_time_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="extent_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="extent_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="extent_type_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="extent_type_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="name_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="name_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="name_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="taxonomy",
            name="name_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="description_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="name_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="taxonomyterm",
            name="name_es",
            field=models.TextField(null=True),
        ),
    ]
